###############################################################################
# Copyright (c) 2026 Willink Transformations and others.
#
# This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     E.D.Willink - initial API and implementation
###############################################################################
# UML2 publisher properties for use by the uml2-promoter job:
#
BUILD_COMMIT=-commit https://github.com/eclipse-uml2/uml2/commit/${env.GIT_COMMIT}
BUILD_PROMOTE=${env.BUILD_URL}artifact/releng/org.eclipse.uml2.build-feature/target/repository
BUILD_REMOTE=-remote genie.uml2@projects-storage.eclipse.org:/home/data/httpd/download.eclipse.org/modeling/mdt/uml2
BUILD_ROOT=/home/jenkins/agent/workspace/justj-promoter/justj-sync
BUILD_TIMESTAMP=-timestamp ${buildTimestamp}
BUILD_TYPE=${env.BUILD_TYPE}
BUILD_URL=${env.BUILD_URL}
